# Generated by Django 3.2.2 on 2021-05-10 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_auto_20210506_1750'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkipVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skip_votes', to='core.room')),
                ('voter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skip_votes', to='core.profile')),
            ],
        ),
    ]
