# Generated by Django 3.2.2 on 2021-05-10 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210506_1750'),
        ('websocket', '0002_auto_20210510_1714'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listener',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active_users', models.ManyToManyField(to='core.Profile')),
                ('room', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.room')),
            ],
        ),
    ]
