# Generated by Django 3.1.7 on 2021-03-16 20:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('is_locked', models.BooleanField(default=False)),
                ('guest_can_pause', models.BooleanField(default=False)),
                ('votes_to_skip', models.PositiveSmallIntegerField(default=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
