# Generated by Django 3.2.2 on 2021-05-14 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210506_1750'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='name',
        ),
        migrations.AddField(
            model_name='profile',
            name='picture',
            field=models.FileField(blank=True, null=True, upload_to='profile_pictures'),
        ),
    ]
